# ADDING & REMOVING ELEMENTS IN ARRAY

In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,1,0]])
print(arr)
print()
# Calculate and print the sum of each column (axis=0) of the array
print(arr.sum(axis = 0))
print()
# Calculate and print the sum of each row (axis=1) of the array
print(arr.sum(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 1 0]]

[12  8  9]

[ 6 15  8]


In [6]:
import numpy as np

a = np.array([10,45,0,26,3,265,15])
print(np.append(a,69))
print(np.append(a,[69,79]))
print(np.insert(a,2,77))   #(array,index,value)
print(np.delete(a,2))

[ 10  45   0  26   3 265  15  69]
[ 10  45   0  26   3 265  15  69  79]
[ 10  45  77   0  26   3 265  15]
[ 10  45  26   3 265  15]


In [16]:
b = np.array([[10,20],[30,40]])
print(b)
print()
print(np.insert(b,1,[50,60]))

[[10 20]
 [30 40]]

[10 50 60 20 30 40]


In [8]:
print(np.insert(b,1,[50,60],axis=0))

[[10 20]
 [50 60]
 [30 40]]


In [9]:
print(np.insert(b,1,[50,60],axis=1))

[[10 50 20]
 [30 60 40]]


In [10]:
print(np.insert(b,1,[50],axis=0))

[[10 20]
 [50 50]
 [30 40]]


In [12]:
print(np.insert(b,[1,2],[50],axis=0))

[[10 20]
 [50 50]
 [30 40]
 [50 50]]


In [13]:
print(np.insert(b,[1,2],[50],axis=1))

[[10 50 20 50]
 [30 50 40 50]]


In [26]:
c = np.array([[10,20],[30,40]])
print(c)
print()
print(np.delete(c,1,axis=0))
print()
print(np.delete(c,1,axis=1))

[[10 20]
 [30 40]]

[[10 20]]

[[10]
 [30]]
