# Joining & Splitting Arrays

In [17]:
import numpy as np

# CONCATENATE
ar1 = np.array([10,62,54,15])
ar2 = np.array([34,2,19,54])
print(np.concatenate([ar1,ar2]))
print(np.concatenate([ar1,ar2],axis = 0))

[10 62 54 15 34  2 19 54]
[10 62 54 15 34  2 19 54]


In [20]:
ar1 = np.array([[10,62],[54,15]])
ar2 = np.array([[34,2],[19,54]])
print(np.concatenate([ar1,ar2],axis = 0))
print(np.concatenate([ar1,ar2],axis = 1))

[[10 62]
 [54 15]
 [34  2]
 [19 54]]
[[10 62 34  2]
 [54 15 19 54]]


In [25]:
# HSTACK
# (HORIZONTAL CONCATENATION)
print(np.hstack([ar1,ar2]))

[[10 62 34  2]
 [54 15 19 54]]


In [24]:
# (VERTICAL CONCATENATION)
print(np.vstack([ar1,ar2]))

[[10 62]
 [54 15]
 [34  2]
 [19 54]]


In [32]:
#SPLITTING
a = np.array([10,65,29,82,2,62,54,15])
b =np.array_split(a,3)
print(b)
print(b[1])

[array([10, 65, 29]), array([82,  2, 62]), array([54, 15])]
[82  2 62]
