# SORTING, SEARCHING & FILTERING ARRAY ELEMENTS

In [2]:
import numpy as np

# SORTING
a = np.array([26,6,29,265,128,2])
print(np.sort(a))
print()
b = np.array([[3,36,26,6,29],[16,32,65,128,2]])
print(np.sort(b))

[  2   6  26  29 128 265]

[[  3   6  26  29  36]
 [  2  16  32  65 128]]


In [29]:
# SEARCHING
n = np.array([3,36,26,6,29,16,2])
s = np.where(n==16)
print(s)
x = np.where(n%2==0)
print(x)

(array([5], dtype=int64),)
(array([1, 2, 3, 5, 6], dtype=int64),)


In [30]:
# SEARCHSORTED
# NOTE: ARRAY MUST BE SORTED

ss = np.array([1,3,4,6,10,18])
print(np.searchsorted(ss,10))

4


In [33]:
# FILTER
# CREATES A NEW ARRAY FROM THE EXISTING ARRAY

f = np.array([10,20,30,40])
# ELEMENTS WHICH WE WANT IN NEW ARRAY WILL ASSIGNNED TRUE VAL.
z = [True, False, True, False]
newarr = f[z]
print(newarr)


[10 30]


In [4]:
arr = np.array([41, 42, 43, 44, 18, 45, 46, 26])
# Initializing an empty list to store boolean values
filar = []
for i in arr:
    if i>42:
        filar.append(True)
    else:
        filar.append(False)

reslarr = arr[filar]
# Print the boolean list indicating which elements are greater than 42
print(filar)
# Print the resulting array containing only elements greater than 42
print(reslarr)

[False, False, True, True, False, True, True, False]
[43 44 45 46]


In [8]:
num = np.array([41, 42, 43, 44, 18, 45, 46, 26])
emp = []
for i in num:
    if i%2==0:
        emp.append(True)
    else:
        emp.append(False)

# Using the boolean list to filter the original array, keeping only even numbers
result = num[emp]
# Printing the boolean list indicating which numbers are even
print(emp)
print(np.sort(result))

[False, True, False, True, True, False, True, True]
[18 26 42 44 46]
