# AGGREGATE FUNCTIONS

In [8]:
import numpy as np

a = np.array([10,30,40,60,90])

print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

230
90
10
5
46.0
[ 10  40  80 140 230]
[      10      300    12000   720000 64800000]


In [2]:
import numpy as np

x = [100,261,154,225,695,655,553,206]
y =[10,26,60,16,30,15,20,40]

price = np.array(x)
quantity = np.array(y)

print(price, "\n" , quantity)
print()
# Calculate the cumulative product of the price and quantity arrays along the first axis (rows)
z = np.cumprod([price, quantity], axis = 0)
print(z)
print()
print(z[1].sum())

[100 261 154 225 695 655 553 206] 
 [10 26 60 16 30 15 20 40]

[[  100   261   154   225   695   655   553   206]
 [ 1000  6786  9240  3600 20850  9825 11060  8240]]

70601
