In [11]:
import numpy as np
import statistics as st

baked_food = [120,128,263,128,143,236,223,231,186]

a = np.array(baked_food)
print(np.mean(a))

# print(np.median(a))
print(np.sort(a))
print(np.median(a))

# MODE - RETURN THE MOST OCCURRING VALUE BUT IF SIMILAR THEN RETURN THE FIRST VAL PRESENT IN THE SEQUENCE
print(st.mode(a))

# MIN THE VAL OF STANDARD DEVIATION BETTER IS THE QUALITY i.e DATA ELEMENTS ARE NOT FAR AWAY FROM MEAN OR AVG VAL
print(np.std(a))

print(np.var(a))
print(52**2)

184.22222222222223
[120 128 128 143 186 223 231 236 263]
186.0
128
52.41665930636467
2747.506172839506
2704


In [15]:
tobacco_consumption = [10,20,40,30,40,50]
deaths = [100,50,125,143,162,70]

# USED TO CHECK THE DEPENDENCY BETWEEN TWO ATTRIBUTES 
print(np.corrcoef([tobacco_consumption, deaths]))


[[1.         0.21631783]
 [0.21631783 1.        ]]


In [17]:
# -1 -> INVERSELY PROPORTIONAL RELATIONSHIP
# 1 -> PROPORTIONAL RELATIONSHIP
# 0 -> NO RELATIONSHIP

price = [100,150,200,300,125]
sales = [10,20,15,4,12]

print(np.corrcoef([price, sales]))


[[ 1.         -0.51967675]
 [-0.51967675  1.        ]]
